name: Build and Test

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:nightly-5.7-bionic
    container: ${{ matrix.image }}
    steps:
      - name: Install SQLite
        run: |
          apt-get -qq update
          apt-get -y -qq install libsqlite3-dev
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Performance Tests
        run: swift run -c release PerformanceTests
